# Generated by Django 4.1.2 on 2023-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("age", models.IntegerField(blank=True, default=0, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=4
                    ),
                ),
                ("interviewer", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
