# Generated by Django 4.1.2 on 2023-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FRONTEND", "0002_questions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="questions",
            constraint=models.UniqueConstraint(
                fields=("name", "question"), name="unique_question"
            ),
        ),
    ]
